name: Builds
on:
  push:
  pull_request:

env:
  # From https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-3-install-wdk
  WDK_INSTALLER_URL: "https://go.microsoft.com/fwlink/?linkid=2307500"

jobs:
  test-msvc-wine-linux-arm-target-host-only:
    runs-on: ubuntu-24.04-arm
    # Use a custom base container for providing wine; the base Wine package
    # in Ubuntu 24.04 is broken on aarch64, see
    # https://bugs.launchpad.net/ubuntu/+source/wine/+bug/2102681 and
    # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1100695. (Fixed in
    # Debian for now, but not yet in Ubuntu.) MSVC on wine on aarch64 requires
    # Wine 8.4 or newer.
    container: ghcr.io/mstorsjo/wine
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update && sudo apt-get install python3 msitools ca-certificates cmake ninja-build winbind meson
          WINE=$(command -v wine64 || command -v wine || false)
          $WINE wineboot
          # Check https://gitlab.winehq.org/wine/wine/-/wikis/Wine-Mono#versions before updating the WINE package!
          curl -s -L -O https://github.com/wine-mono/wine-mono/releases/download/wine-mono-10.4.1/wine-mono-10.4.1-x86.msi
          $WINE msiexec /i wine-mono-10.4.1-x86.msi
      - uses: actions/checkout@v6
      - name: Download MSVC
        run: |
          ./vsdownload.py --accept-license --architecture host --dest $(pwd)/msvc
          ./install.sh $(pwd)/msvc
      - name: Test using the installed tools
        run: |
          test/test.sh $(pwd)/msvc
      # Intentionally not storing any artifacts with the downloaded tools;
      # the installed files aren't redistributable!
